#!/bin/bash

trap exit__ ERR

exit__()
{
	echo "Something is wrong. Exiting..."
	exit -1
}

list_dirs=`ls -I backup -I shared -I doc -I clean -I build -I setup -I run-all -I README.md -I cpp-format -I vim-copy -I .vimrc`

for local_dir  in ${list_dirs[@]}
do
	cd ${local_dir}/build/Debug
	./build
	cd ../Release/
	./build
	cd ../../../
done

