#!/bin/bash

trap exit__ ERR

exit__()
{
	echo "Something is wrong. Exiting..."
	exit -1
}

list_dirs=`ls -I backup -I shared -I doc -I clean -I build -I setup -I run-all -I README.md`

lock=1

for local_dir  in ${list_dirs[@]}
do

	if [ ${local_dir} == abc ]; then
		lock=0
	fi

	if [ ${lock} == 0 ]; then
		echo "${local_dir}..."
		cd ${local_dir}/bin/Release
		./run-all
		cd ../../../
	fi

done

