#!/bin/bash

trap exit__ ERR

exit__()
{
	echo "Something is wrong. Exiting..."
	exit -1
}

list_dirs=`ls -I backup -I shared -I doc -I clean -I build -I setup -I run-all -I README.md -I cpp-format -I vim-copy -I .vimrc`

shared_include=`ls shared/include`
shared_src=`ls shared/src`

for local_dir  in ${list_dirs[@]}
do
	echo Setting up ${local_dir} ...
	cp .vimrc ${local_dir}/.
done

